[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "TODO Project Name"
version = "1.0.22"
authors = [
  { name = "Mohammed Alzakariya", email = "lanhikarixx@gmail.com" }
]
description = "TODO Description"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "Result"
]
